name: BIOPEP Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Create R library folder
        run: |
          mkdir -p Rlibs

      - name: Install packages (FORCED LIB PATH)
        run: |
          Rscript -e '
          .libPaths("Rlibs");

          install.packages(c(
            "rvest",
            "httr",
            "stringr",
            "dplyr",
            "purrr",
            "openxlsx"
          ), repos="https://cloud.r-project.org");
          '

      - name: Test rvest load
        run: |
          Rscript -e '
          .libPaths("Rlibs");
          library(rvest);
          cat("rvest OK\n");
          '

      - name: Run scraper
        run: |
          Rscript -e '.libPaths("Rlibs"); source("scraper.R")'

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: BIOPEP-results
          path: BIOPEP_ALL_sequences.xlsx
