name: BIOPEP Scraper Pipeline

on:
  workflow_dispatch:

jobs:
  scrape:

    runs-on: ubuntu-latest

    container:
      image: rocker/tidyverse:latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install missing R packages
        run: |
          Rscript -e 'install.packages(c(
            "furrr",
            "future",
            "openxlsx"
          ), repos="https://cloud.r-project.org")'

      - name: Verify rvest
        run: |
          Rscript -e 'library(rvest); cat("RVEST WORKS\n")'

      - name: Run scraper
        run: |
          Rscript biopep_parallel.R

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: BIOPEP-results

          path: BIOPEP_sequences.xlsx
